package it.unibo.the100dayswar.commons.utilities.api;

import it.unibo.the100dayswar.commons.patterns.Observable;
import it.unibo.the100dayswar.model.player.api.Player;

/**
 * An interface for all the objects that can generate resources.
 */
public interface ResourceGenerator extends Observable<Player> {
    /**
     * Get the amount of resources generated by the object.
     * 
     * @return the amount of resources generated
     */
    int getAmount();
}
